version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: lumina_postgres
    restart: always
    environment:
      POSTGRES_USER: lumina
      POSTGRES_PASSWORD: lumina123
      POSTGRES_DB: lumina_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    container_name: lumina_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: lumina
      MONGO_INITDB_ROOT_PASSWORD: lumina123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: lumina_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  mongo_data:
  redis_data:
